import AppBar from "@/components/AppBar";
import "./globals.css";
import ThemeRegistry from '@/components/ThemeRegistry/ThemeRegistry';
import Providers from "@/components/Providers";

export const metadata = {
  title: "Next-Auth Tutorial",
  description: "Generated by Sakura Dev",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <Providers>
            <AppBar />
            {children}
          </Providers>
        </ThemeRegistry>
      </body>
    </html>
  );
}